// src/app/contact/contact.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css']
})

export class ContactComponent {
}
<div class="bg-gray-800 p-4">
    <h1 class="font-oswald text-white text-xl pb-4">
        Contact
    </h1>

    <div class="text-white">
        <h3>
            Email: lukeinlow@gmail.com
        </h3>
         
        <h3>
            Discord: Li#9240
        </h3>
    
        <h3>
            Phone #: +1(703)-595-3043
        </h3>
    </div>

    <a class="text-white underline italic" href="https://github.com/Lii02/portfolio" target="_blank">
        Source Code
    </a>

    <div class="flex justify-center">
        <a class="mx-2" href="https://github.com/Lii02" target="_blank">
            <img class="w-16 h-16" src="assets/icons/github-mark-white.png" alt="GitHub Page" />
        </a>
    
        <a class="mx-2" href="https://lii02dev.itch.io/" target="_blank">
            <img class="w-16 h-16" src="assets/icons/itchio.png" alt="Itch.io" />
        </a>

        <a class="mx-2" href="https://www.linkedin.com/in/luke-inlow-709b81100/" target="_blank">
            <img class="w-16 h-16" src="assets/icons/linkedin.png" alt="LinkedIn" />
        </a>
    </div>
</div>

// app/contact/page.tsx
import '@/styles/contact.css';

// Logos
import Image from 'next/image';
import github from '@/public/github-mark-white.png';
import linkedin from '@/public/linkedin.png';
import itchio from '@/public/itchio.png';
import listudios from '@/public/SquareInverted.png';

export default function Contact() {
	return (
		<div className='Contact Section'>
			<section>
				<h2>
					Email:{' '}
					<a href='mailto:lukeinlow@gmail.com' className='Email'>
						lukeinlow@gmail.com
					</a>
				</h2>
				<h2>Discord: li02</h2>
				<a href='https://github.com/Lii02/portfolio' target='_blank'>
					<h2 className='LinkButton'>Source Code</h2>
				</a>
			</section>

			<section className='Socials'>
				<h2>Socials</h2>
				<a href='https://github.com/Lii02' target='_blank'>
					<Image src={github} alt='GitHub' />
				</a>

				<a
					href='https://www.linkedin.com/in/luke-inlow-709b81100/'
					target='_blank'>
					<Image src={linkedin} alt='LinkedIn' />
				</a>

				<a href='https://lii02dev.itch.io/' target='_blank'>
					<Image src={itchio} alt='Itch.io' />
				</a>

				<a href='https://listudios.io/' target='_blank'>
					<Image src={listudios} alt='Li Studios' />
				</a>
			</section>
		</div>
	);
}
