// src/app/contact/contact.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrls: ['./contact.component.css']
})

export class ContactComponent {
}
<div class="bg-gray-800 p-4">
    <h1 class="font-oswald text-white text-xl pb-4">
        Contact
    </h1>

    <div class="text-white">
        <h3>
            Email: lukeinlow@gmail.com
        </h3>
         
        <h3>
            Discord: Li#9240
        </h3>
    
        <h3>
            Phone #: +1(703)-595-3043
        </h3>
    </div>

    <a class="text-white underline italic" href="https://github.com/Lii02/portfolio" target="_blank">
        Source Code
    </a>

    <div class="flex justify-center">
        <a class="mx-2" href="https://github.com/Lii02" target="_blank">
            <img class="w-16 h-16" src="assets/icons/github-mark-white.png" alt="GitHub Page" />
        </a>
    
        <a class="mx-2" href="https://lii02dev.itch.io/" target="_blank">
            <img class="w-16 h-16" src="assets/icons/itchio.png" alt="Itch.io" />
        </a>

        <a class="mx-2" href="https://www.linkedin.com/in/luke-inlow-709b81100/" target="_blank">
            <img class="w-16 h-16" src="assets/icons/linkedin.png" alt="LinkedIn" />
        </a>
    </div>
</div>

// src/components/contact.tsx
import React from 'react';

import GithubIcon from '../assets/icons/github-mark-white.png';
import ItchioIcon from '../assets/icons/itchio.png';
import LinkedinIcon from '../assets/icons/linkedin.png';
import { headerStyle, iconStyle } from '../styles';

function Contact() {
  return (
    <div className='font-roboto bg-gradient-to-t from-gray-400 to-gray-500'>
      <h1 className={headerStyle}>
        Contact
      </h1>

      <h3>
        Email: lukeinlow@gmail.com
      </h3>

      <h3>
        Discord: li02
      </h3>

      <a className='text-white underline italic' href='https://github.com/Lii02/portfolio' target='_blank'>
        Source Code
      </a>

      <div className='flex justify-center'>
        <a className={iconStyle} href='https://github.com/Lii02' target='_blank'>
          <img src={GithubIcon} alt='GitHub' />
        </a>

        <a className={iconStyle} href='https://lii02dev.itch.io/' target='_blank'>
          <img src={ItchioIcon} alt='itch.io' />
        </a>

        <a className={iconStyle} href='https://www.linkedin.com/in/luke-inlow-709b81100/' target='_blank'>
          <img src={LinkedinIcon} alt='LinkedIn' />
        </a>
      </div>
    </div>
  );
}

export default Contact;
