// src/app/projects/projects.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  styleUrls: ['./projects.component.css']
})

export class ProjectsComponent {
}
<div class="bg-gray-700">
    <h1 class="flex font-oswald text-xl text-white text-center justify-center py-4">
        Projects
    </h1>

    <div class="grid grid-cols-2">
        <app-project projectName="Sign In System" projectDescriptionSrc="assets/descriptions/signin.txt" image="assets/images/SignIn.png" link="https://github.com/Lii02/signin-system" />
        <app-project projectName="FPS Dungeon" projectDescriptionSrc="assets/descriptions/fps.txt" image="assets/images/FPSDungeon.png" link="https://lii02dev.itch.io/fps-dungeon" />
        <app-project projectName="Hoddsmimir" projectDescriptionSrc="assets/descriptions/hoddsmimir.txt" image="assets/images/Hoddsmimir.png" link="https://lii02dev.itch.io/hoddsmimir" />
        <app-project projectName="Game Of Life" projectDescriptionSrc="assets/descriptions/gol.txt" image="assets/images/GOL.png" link="https://github.com/Lii02/ConwayGOL" />
        <app-project projectName="Vulkan Renderer" projectDescriptionSrc="assets/descriptions/renderer.txt" image="assets/images/VulkanRenderer.jpg" link="https://github.com/Lii02/LevelRenderer" />
        <app-project projectName="Flappy Bird Clone" projectDescriptionSrc="assets/descriptions/flappy.txt" image="assets/images/FlappyBirdClone.png" link="https://lii02dev.itch.io/flappy-bird-clone" />
    </div>
</div>

// src/components/projects.tsx
import React from 'react';
import Project from './project';

// Project images and description files
import SignInImage from '../assets/images/SignIn.png';
import SignInDesc from '../assets/descriptions/signin.txt';

import FPSDungeonImage from '../assets/images/FPSDungeon.png';
import FPSDungeonDesc from '../assets/descriptions/fps.txt';

import GOLImage from '../assets/images/GOL.png';
import GOLDesc from '../assets/descriptions/GOL.txt';

import VulkanRendererImage from '../assets/images/VulkanRenderer.jpg';
import VulkanRendererDesc from '../assets/descriptions/renderer.txt';

import HoddsmimirImage from '../assets/images/Hoddsmimir.png';
import HoddsmimirDesc from '../assets/descriptions/hoddsmimir.txt';

import FlappyBirdImage from '../assets/images/FlappyBirdClone.png';
import FlappyBirdDesc from '../assets/descriptions/flappy.txt';

function Projects() {
  return (
    <div className='bg-gray-500'>
      <h1 className='flex font-roboto text-xl text-white text-center justify-center'>
        Projects
      </h1>
      
      <div className='grid grid-cols-2'>
        <Project projectName='Sign In System' descriptionSrc={SignInDesc} link='https://github.com/Lii02/signin-system' image={SignInImage} />
        <Project projectName='FPS Dungeon' descriptionSrc={FPSDungeonDesc} link='' image={FPSDungeonImage} />
        <Project projectName='GOL' descriptionSrc={GOLDesc} link='https://github.com/Lii02/ConwayGOL' image={GOLImage} />
        <Project projectName='Vulkan Renderer' descriptionSrc={VulkanRendererDesc} link='https://github.com/Lii02/LevelRenderer' image={VulkanRendererImage} />
        <Project projectName='Hoddsmimir' descriptionSrc={HoddsmimirDesc} link='https://lii02dev.itch.io/hoddsmimir"' image={HoddsmimirImage} />
        <Project projectName='Flappy Bird Clone' descriptionSrc={FlappyBirdDesc} link='https://lii02dev.itch.io/flappy-bird-clone' image={FlappyBirdImage} />
      </div>
    </div>
  );
}

export default Projects;
