// src/components/project.tsx
import React, { useEffect, useState } from 'react';

function Project({ projectName, descriptionSrc, link, image }) {
  const [descriptionText, setDescriptionText] = useState<string>('');

  useEffect(() => {
    const loadDesc = async () => {
      try {
        const res = await fetch(descriptionSrc);
        const text = await res.text();
        setDescriptionText(text);
      } catch (error) {
        console.error(`Error loading description file: ${descriptionSrc} Error: ${error}`);
      }
    }

    loadDesc();
  });

  return (
    <div className='bg-neutral-800 rounded-md'>
      <p className='font-roboto font-bold italic text-gray-200 text-center'>
        { projectName }
      </p>

      <a href={link} target='_blank'>
        <img className='rounded-3xl scale-75 hover:rounded-xl hover:scale-90 transition-all' src={image} />
      </a>

      <p className='text-gray-100 font-roboto'>
        <span className='font-bold'>Description:</span> {descriptionText}
      </p>
    </div>
  );
}

export default Project;

// src/app/project/project.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-project',
  templateUrl: './project.component.html',
  styleUrls: ['./project.component.css']
})

export class ProjectComponent implements OnInit {
  @Input() projectName: string;
  @Input() projectDescriptionSrc: string;
  @Input() image: string;
  @Input() link: string;

  projectDescription: string;

  constructor(private http: HttpClient) { }

  ngOnInit(): void {
    // Retrieved the description file from assets
    this.http.get(this.projectDescriptionSrc, { responseType: 'text' })
      .subscribe(fileContent => {
        this.projectDescription = fileContent;
    })
  }
}
<div class="bg-neutral-800 rounded-md m-2 p-2">
    <p class="font-montserrat font-bold italic text-gray-200 text-center">
        {{projectName}}
    </p>

    <a href={{link}} target="_blank">
        <img class="project-image" src={{image}} />
    </a>

    <p class="text-gray-100 p-4">
        <span class="font-bold">Description:</span> {{projectDescription}}
    </p>
</div>
